image: golang:latest
variables:
  REPO_NAME: gitlab.com/jckimble/signalgateway
stages:
    - build

compile:
    stage: build
    before_script:
      - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
      - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
      - cd $GOPATH/src/$REPO_NAME
      - go get
    script:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o $CI_PROJECT_DIR/signalgateway .
    artifacts:
      paths:
        - signalgateway
